# Generated by Django 5.1.11 on 2025-08-12 11:43

import django.db.models.deletion
import services.attachments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='The ID of the entity this attachment belongs to')),
                ('attachment_type', models.CharField(choices=[('file', 'File'), ('link', 'Link')], default='file', help_text='Type of attachment - file or link', max_length=10)),
                ('file', models.FileField(blank=True, help_text='The uploaded file (for file attachments only)', null=True, upload_to=services.attachments.models.attachment_upload_path)),
                ('link_url', models.URLField(blank=True, help_text='External URL (for link attachments only)', max_length=2000, null=True)),
                ('original_filename', models.CharField(help_text='Original filename for files or user-provided title for links', max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes (for files only)', null=True)),
                ('content_type_header', models.CharField(blank=True, help_text='MIME type of the file (for files only)', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the attachment')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the attachment was uploaded')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the attachment was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this attachment is active')),
                ('content_type', models.ForeignKey(help_text='The type of entity this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this attachment', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'db_table': 'attachment',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='idx_attachment_content'), models.Index(fields=['uploaded_by'], name='idx_attachment_uploader'), models.Index(fields=['uploaded_at'], name='idx_attachment_uploaded'), models.Index(fields=['is_active'], name='idx_attachment_active'), models.Index(fields=['content_type_header'], name='idx_attachment_mime')],
                'constraints': [models.CheckConstraint(condition=models.Q(('file_size__gt', 0), ('file_size__isnull', True), _connector='OR'), name='attachment_file_size_positive'), models.CheckConstraint(condition=models.Q(models.Q(('attachment_type', 'file'), ('file__gt', ''), ('file__isnull', False), ('link_url__isnull', True)), models.Q(('attachment_type', 'link'), ('file__isnull', True), ('link_url__gt', ''), ('link_url__isnull', False)), models.Q(('attachment_type', 'link'), ('file', ''), ('link_url__gt', ''), ('link_url__isnull', False)), _connector='OR'), name='attachment_type_consistency')],
            },
        ),
    ]
