# Generated by Django 5.1.11 on 2025-08-12 11:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Email subject line', max_length=255)),
                ('content', models.TextField(help_text='Email content/body')),
                ('email_address', models.EmailField(help_text='From/To email address (depending on direction)', max_length=254)),
                ('direction', models.CharField(choices=[('inbound', 'Received'), ('outbound', 'Sent'), ('draft', 'Draft')], help_text='Email direction (inbound/outbound/draft)', max_length=10)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('received', 'Received'), ('read', 'Read'), ('replied', 'Replied'), ('forwarded', 'Forwarded'), ('draft', 'Draft'), ('failed', 'Failed')], default='sent', help_text='Email status', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Email priority level', max_length=10)),
                ('contact_name', models.CharField(blank=True, help_text='Contact name (if not linked to CRM contact)', max_length=255)),
                ('email_date', models.DateField(default=django.utils.timezone.now, help_text='Date of the email')),
                ('email_time', models.TimeField(default=django.utils.timezone.now, help_text='Time of the email')),
                ('cc_addresses', models.TextField(blank=True, help_text='CC email addresses (comma-separated)')),
                ('bcc_addresses', models.TextField(blank=True, help_text='BCC email addresses (comma-separated)')),
                ('message_id', models.CharField(blank=True, help_text='Original email message ID', max_length=255)),
                ('thread_id', models.CharField(blank=True, help_text='Email thread/conversation ID', max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='The ID of the entity this email is related to (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the email record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the email record was last updated')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Email tags/categories')),
                ('follow_up_required', models.BooleanField(default=False, help_text='Whether this email requires follow-up')),
                ('follow_up_date', models.DateTimeField(blank=True, help_text='When to follow up (if required)', null=True)),
                ('follow_up_notes', models.TextField(blank=True, help_text='Follow-up notes and action items')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this email record is active')),
                ('contact', models.ForeignKey(blank=True, help_text='Contact this email is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='contacts.contact')),
                ('content_type', models.ForeignKey(blank=True, help_text='The type of entity this email is related to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(help_text='User who logged this email', on_delete=django.db.models.deletion.CASCADE, related_name='created_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'db_table': 'email',
                'ordering': ['-email_date', '-email_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the comment was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the comment was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this comment is active')),
                ('author', models.ForeignKey(help_text='User who wrote this comment', on_delete=django.db.models.deletion.CASCADE, related_name='email_comments', to=settings.AUTH_USER_MODEL)),
                ('email', models.ForeignKey(help_text='The email this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='emails.email')),
            ],
            options={
                'verbose_name': 'Email Comment',
                'verbose_name_plural': 'Email Comments',
                'db_table': 'email_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['direction'], name='idx_email_direction'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['status'], name='idx_email_status'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['priority'], name='idx_email_priority'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['created_by'], name='idx_email_creator'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['contact'], name='idx_email_contact'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['email_date'], name='idx_email_date'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['email_time'], name='idx_email_time'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['created_at'], name='idx_email_created'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_email_content'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['is_active'], name='idx_email_active'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['follow_up_required'], name='idx_email_followup'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['follow_up_date'], name='idx_email_followup_date'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['email_address'], name='idx_email_address'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['subject'], name='idx_email_subject'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['thread_id'], name='idx_email_thread'),
        ),
        migrations.AddConstraint(
            model_name='email',
            constraint=models.CheckConstraint(condition=models.Q(('contact__isnull', False), models.Q(('contact_name__isnull', False), models.Q(('contact_name', ''), _negated=True)), _connector='OR'), name='email_contact_required'),
        ),
        migrations.AddIndex(
            model_name='emailcomment',
            index=models.Index(fields=['email'], name='idx_emailcomment_email'),
        ),
        migrations.AddIndex(
            model_name='emailcomment',
            index=models.Index(fields=['author'], name='idx_emailcomment_author'),
        ),
        migrations.AddIndex(
            model_name='emailcomment',
            index=models.Index(fields=['created_at'], name='idx_emailcomment_created'),
        ),
        migrations.AddIndex(
            model_name='emailcomment',
            index=models.Index(fields=['is_active'], name='idx_emailcomment_active'),
        ),
    ]
