# Generated by Django 5.1.11 on 2025-08-12 11:43

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255)),
                ('account_owner_alias', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_street', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_zip_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_country', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_street', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_zip_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_accounts', to=settings.AUTH_USER_MODEL)),
                ('parent_account', models.ForeignKey(blank=True, db_column='parent_account_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_accounts', to='accounts.account')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'account',
                'ordering': ['account_name'],
                'indexes': [models.Index(fields=['owner'], name='idx_account_owner'), models.Index(fields=['created_at'], name='idx_account_created'), models.Index(fields=['account_name'], name='idx_account_name'), models.Index(fields=['industry'], name='idx_account_industry')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('account_name'), name='unique_account_name_per_schema')],
            },
        ),
    ]
