# Generated by Django 5.1.11 on 2025-08-12 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0001_initial'),
        ('customers', '0001_initial'),
        ('deals', '0001_initial'),
        ('estimates', '0001_initial'),
        ('products', '0001_initial'),
        ('sales_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Shipping fee for this document', max_digits=10)),
                ('shipping_vat_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='VAT percentage for shipping (0-100)', max_digits=5)),
                ('rush_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Rush processing fee for this document', max_digits=10)),
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text="Unique invoice number, e.g., 'INV-2024-001'", max_length=50, unique=True)),
                ('po_number', models.CharField(blank=True, help_text='Customer purchase order number', max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', help_text='Current status of the invoice', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of all line item subtotals (before VAT)', max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of all line item totals (includes VAT)', max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid towards this invoice', max_digits=14)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining amount due (total_amount - amount_paid)', max_digits=14)),
                ('invoice_date', models.DateField(help_text='Date when invoice was created')),
                ('due_date', models.DateField(help_text='Due date for payment')),
                ('paid_date', models.DateField(blank=True, help_text='Date when invoice was fully paid', null=True)),
                ('payment_terms', models.CharField(choices=[('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('due_on_receipt', 'Due on Receipt'), ('custom', 'Custom Terms')], default='net_30', help_text='Payment terms for this invoice', max_length=20)),
                ('custom_payment_terms', models.CharField(blank=True, help_text='Custom payment terms description', max_length=200, null=True)),
                ('billing_attention', models.CharField(blank=True, help_text='Billing attention to', max_length=255, null=True)),
                ('billing_street', models.CharField(blank=True, help_text='Billing street address', max_length=255, null=True)),
                ('billing_city', models.CharField(blank=True, help_text='Billing city', max_length=100, null=True)),
                ('billing_state_province', models.CharField(blank=True, help_text='Billing state or province', max_length=100, null=True)),
                ('billing_zip_postal_code', models.CharField(blank=True, help_text='Billing ZIP or postal code', max_length=20, null=True)),
                ('billing_country', models.CharField(blank=True, help_text='Billing country', max_length=100, null=True)),
                ('shipping_attention', models.CharField(blank=True, help_text='Shipping attention to', max_length=255, null=True)),
                ('shipping_street', models.CharField(blank=True, help_text='Shipping street address', max_length=255, null=True)),
                ('shipping_city', models.CharField(blank=True, help_text='Shipping city', max_length=100, null=True)),
                ('shipping_state_province', models.CharField(blank=True, help_text='Shipping state or province', max_length=100, null=True)),
                ('shipping_zip_postal_code', models.CharField(blank=True, help_text='Shipping ZIP or postal code', max_length=20, null=True)),
                ('shipping_country', models.CharField(blank=True, help_text='Shipping country', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for this invoice', null=True)),
                ('terms_conditions', models.TextField(blank=True, help_text='Terms and conditions for this invoice', null=True)),
                ('reference_number', models.CharField(blank=True, help_text='External reference number', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='account_id', help_text='Account this invoice is for (required)', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.account')),
                ('contact', models.ForeignKey(blank=True, db_column='contact_id', help_text='Primary contact person for this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', help_text='Customer this invoice is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customers.financecontact')),
                ('deal', models.ForeignKey(blank=True, db_column='deal_id', help_text='Associated deal/opportunity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='deals.deal')),
                ('estimate', models.ForeignKey(blank=True, db_column='estimate_id', help_text='Source estimate this invoice was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='estimates.estimate')),
                ('owner', models.ForeignKey(blank=True, db_column='owner_id', help_text='Sales rep/owner of this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_invoices', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(blank=True, db_column='sales_order_id', help_text='Source sales order this invoice was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales_orders.salesorder')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoice',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('line_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, help_text='Custom description (can override product description)', null=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity invoiced', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit (can override product price)', max_digits=10)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (0-100)', max_digits=5)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='VAT percentage for this line item (0-100)', max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated VAT amount for this line item', max_digits=14)),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='(quantity × unit_price) - discount', max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=0.0, help_text='line_subtotal + vat_amount', max_digits=14)),
                ('sort_order', models.PositiveIntegerField(default=1, help_text='Display order of this line item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(db_column='invoice_id', help_text='Invoice this line item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoice')),
                ('product', models.ForeignKey(db_column='product_id', help_text='Product/service for this line item', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_line_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Invoice Line Item',
                'verbose_name_plural': 'Invoice Line Items',
                'db_table': 'invoice_line_item',
                'ordering': ['sort_order', 'line_item_id'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=14)),
                ('payment_date', models.DateField(help_text='Date when payment was received')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('other', 'Other')], help_text='Payment method used', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference number', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Payment notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(db_column='invoice_id', help_text='Invoice this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Payment',
                'verbose_name_plural': 'Invoice Payments',
                'db_table': 'invoice_payment',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='idx_invoice_number'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['account'], name='idx_invoice_account'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer'], name='idx_invoice_customer'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['deal'], name='idx_invoice_deal'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['contact'], name='idx_invoice_contact'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['owner'], name='idx_invoice_owner'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['estimate'], name='idx_invoice_estimate'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['sales_order'], name='idx_invoice_sales_order'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_at'], name='idx_invoice_created'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='idx_invoice_status'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='idx_invoice_date'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='idx_invoice_due_date'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['paid_date'], name='idx_invoice_paid_date'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('invoice_number',), name='unique_invoice_number_per_schema'),
        ),
        migrations.AddIndex(
            model_name='invoicelineitem',
            index=models.Index(fields=['invoice'], name='idx_inv_line_invoice'),
        ),
        migrations.AddIndex(
            model_name='invoicelineitem',
            index=models.Index(fields=['product'], name='idx_inv_line_product'),
        ),
        migrations.AddIndex(
            model_name='invoicelineitem',
            index=models.Index(fields=['vat_rate'], name='idx_inv_line_vat_rate'),
        ),
        migrations.AddIndex(
            model_name='invoicelineitem',
            index=models.Index(fields=['sort_order'], name='idx_inv_line_sort_order'),
        ),
        migrations.AddIndex(
            model_name='invoicepayment',
            index=models.Index(fields=['invoice'], name='idx_payment_invoice'),
        ),
        migrations.AddIndex(
            model_name='invoicepayment',
            index=models.Index(fields=['payment_date'], name='idx_payment_date'),
        ),
        migrations.AddIndex(
            model_name='invoicepayment',
            index=models.Index(fields=['payment_method'], name='idx_payment_method'),
        ),
        migrations.AddIndex(
            model_name='invoicepayment',
            index=models.Index(fields=['created_at'], name='idx_payment_created'),
        ),
    ]
