# Generated by Django 5.1.11 on 2025-08-12 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(help_text='Primary display name for the customer', max_length=255)),
                ('customer_type', models.CharField(choices=[('business', 'Business'), ('individual', 'Individual')], default='business', max_length=20)),
                ('customer_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', max_length=3)),
                ('payment_terms', models.CharField(choices=[('immediate', 'Immediate'), ('net15', 'Net 15 Days'), ('net30', 'Net 30 Days'), ('net60', 'Net 60 Days'), ('net90', 'Net 90 Days')], default='net30', max_length=20)),
                ('vat_treatment', models.CharField(blank=True, choices=[('uk', 'UK'), ('overseas', 'Overseas')], help_text='VAT treatment classification', max_length=20, null=True)),
                ('vat_registration_number', models.CharField(blank=True, help_text='VAT registration number', max_length=50, null=True)),
                ('billing_attention', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_street', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_zip_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_attention', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_street', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_zip_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_country', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_since', models.DateField(auto_now_add=True)),
                ('last_transaction_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_column='owner_id', help_text='Customer owner/assignee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_customers', to=settings.AUTH_USER_MODEL)),
                ('primary_contact', models.ForeignKey(blank=True, db_column='primary_contact_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_as_primary', to='contacts.contact')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['account'], name='idx_customer_account'), models.Index(fields=['primary_contact'], name='idx_customer_primary_contact'), models.Index(fields=['owner'], name='idx_customer_owner'), models.Index(fields=['created_at'], name='idx_customer_created'), models.Index(fields=['display_name'], name='idx_customer_display_name'), models.Index(fields=['customer_status'], name='idx_customer_status'), models.Index(fields=['customer_type'], name='idx_customer_type'), models.Index(fields=['currency'], name='idx_customer_currency')],
                'constraints': [models.UniqueConstraint(fields=('account', 'primary_contact'), name='unique_customer_account_contact_per_schema')],
            },
        ),
    ]
