# Generated by Django 5.1.11 on 2025-08-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_unique_customer_account_contact_per_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='portal_language',
            field=models.CharField(blank=True, default='en', help_text='Preferred language for portal (en, es, fr, etc.)', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='portal_status',
            field=models.CharField(blank=True, choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='disabled', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='social_media',
            field=models.JSONField(blank=True, default=dict, help_text='Social media profiles (linkedin, twitter, facebook, etc.)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tags for categorization'),
        ),
    ]
