# Generated by Django 5.1.11 on 2025-08-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_duplicate_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='idx_crm_account_id',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='idx_crm_contact_id',
        ),
    ]
