# Generated by Django 5.1.11 on 2025-08-18 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_remove_customer_idx_crm_account_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="link_created_at",
            field=models.DateTimeField(
                blank=True, help_text="When the link was created", null=True
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="link_created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the link",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entity_links_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="linked_entity",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to corresponding vendor/customer record for same entity",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_counterpart",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="contact_type",
            field=models.CharField(
                choices=[("customer", "Customer"), ("vendor", "Vendor")],
                db_index=True,
                default="customer",
                help_text="Record type: Customer or Vendor (never both)",
                max_length=20,
            ),
        ),
    ]
