# Generated by Django 5.1.11 on 2025-08-19 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0003_remove_accounttransaction_finance_acc_custome_5e65b0_idx_and_more",
        ),
        ("accounts", "0001_initial"),
        ("contacts", "0001_initial"),
        ("customers", "0007_rename_to_financecontact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financecontact",
            options={
                "ordering": ["display_name"],
                "verbose_name": "Finance Contact",
                "verbose_name_plural": "Finance Contacts",
            },
        ),
        migrations.RemoveConstraint(
            model_name="financecontact",
            name="unique_customer_account_contact_per_schema",
        ),
        migrations.RenameIndex(
            model_name="financecontact",
            new_name="idx_fincontact_account",
            old_name="idx_customer_account",
        ),
        migrations.RenameIndex(
            model_name="financecontact",
            new_name="idx_fincontact_primary_contact",
            old_name="idx_customer_primary_contact",
        ),
        migrations.RenameIndex(
            model_name="financecontact",
            new_name="idx_fincontact_owner",
            old_name="idx_customer_owner",
        ),
        migrations.RenameIndex(
            model_name="financecontact",
            new_name="idx_fincontact_created",
            old_name="idx_customer_created",
        ),
        migrations.RenameIndex(
            model_name="financecontact",
            new_name="idx_fincontact_display_name",
            old_name="idx_customer_display_name",
        ),
        migrations.RenameIndex(
            model_name="financecontact",
            new_name="idx_fincontact_status",
            old_name="idx_customer_status",
        ),
        migrations.RenameIndex(
            model_name="financecontact",
            new_name="idx_fincontact_type",
            old_name="idx_customer_type",
        ),
        migrations.RenameIndex(
            model_name="financecontact",
            new_name="idx_fincontact_currency",
            old_name="idx_customer_currency",
        ),
        migrations.RenameIndex(
            model_name="financecontact",
            new_name="idx_fincontact_contact_type",
            old_name="idx_customer_contact_type",
        ),
        migrations.AlterField(
            model_name="financecontact",
            name="linked_entity",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to corresponding vendor (if this is customer) or customer (if this is vendor)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_counterpart",
                to="customers.financecontact",
            ),
        ),
        migrations.AddConstraint(
            model_name="financecontact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("account__isnull", False)),
                fields=("account", "primary_contact"),
                name="unique_fincontact_account_contact_per_schema",
            ),
        ),
        migrations.AlterModelTable(
            name="financecontact",
            table="finance_contact",
        ),
    ]
