# Generated by Django 5.1.11 on 2025-08-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0008_alter_financecontact_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="financecontact",
            name="unique_fincontact_account_contact_per_schema",
        ),
        migrations.RemoveIndex(
            model_name="financecontact",
            name="idx_fincontact_primary_contact",
        ),
        migrations.RemoveField(
            model_name="financecontact",
            name="contact_name",
        ),
        migrations.RemoveField(
            model_name="financecontact",
            name="email",
        ),
        migrations.RemoveField(
            model_name="financecontact",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="financecontact",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="financecontact",
            name="mobile",
        ),
        migrations.RemoveField(
            model_name="financecontact",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="financecontact",
            name="primary_contact",
        ),
    ]
