# Generated by Django 5.1.11 on 2025-08-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit - unique identifier', max_length=100, null=True, unique=True),
        ),
    ]
