# Generated by Django 5.1.11 on 2025-08-21 13:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_items', '0002_alter_item_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='part_number',
        ),
        migrations.AddField(
            model_name='item',
            name='dimension_unit',
            field=models.CharField(blank=True, choices=[('cm', 'Centimeters'), ('in', 'Inches')], default='cm', help_text='Unit for dimensions (length, width, height)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product height', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='item',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product length', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='item',
            name='mpn',
            field=models.CharField(blank=True, help_text='Manufacturer Part Number (MPN)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Product weight', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AddField(
            model_name='item',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilograms'), ('lbs', 'Pounds'), ('g', 'Grams'), ('oz', 'Ounces')], default='kg', help_text='Unit for weight', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Product width', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
