# Generated by Django 5.1.11 on 2025-08-21 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0010_remove_financecontact_contact_persons_contactperson"),
        (
            "inventory_items",
            "0003_remove_item_part_number_item_dimension_unit_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="sales_description",
            field=models.TextField(
                blank=True,
                help_text="Description for sales transactions (quotes, invoices, etc.)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="purchase_description",
            field=models.TextField(
                blank=True,
                help_text="Description for purchase transactions (bills, purchase orders, etc.)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="vendor_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Preferred vendor/supplier for purchasing this item",
                limit_choices_to=models.Q(
                    ("contact_type", "vendor"),
                    ("contact_type", "customer_and_vendor"),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplied_items",
                to="customers.financecontact",
            ),
        ),
    ]
