# Generated by Django 5.1.11 on 2025-08-22 14:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaxGroup",
            fields=[
                (
                    "tax_group_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tax_group_name", models.CharField(max_length=255)),
                (
                    "tax_group_percentage",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tax Group",
                "verbose_name_plural": "Tax Groups",
                "db_table": "finance_tax_groups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "tax_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tax_name", models.CharField(max_length=255)),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[("tax", "Tax"), ("compound_tax", "Compound Tax")],
                        default="tax",
                        max_length=20,
                    ),
                ),
                ("is_value_added", models.BooleanField(default=True)),
                ("is_default_tax", models.BooleanField(default=False)),
                ("is_editable", models.BooleanField(default=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("country_code", models.CharField(blank=True, max_length=2, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("update_recurring_invoice", models.BooleanField(default=False)),
                ("update_recurring_expense", models.BooleanField(default=False)),
                ("update_draft_invoice", models.BooleanField(default=False)),
                ("update_recurring_bills", models.BooleanField(default=False)),
                ("update_draft_so", models.BooleanField(default=False)),
                ("update_subscription", models.BooleanField(default=False)),
                ("update_project", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tax",
                "verbose_name_plural": "Taxes",
                "db_table": "finance_taxes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tax_name"], name="finance_tax_tax_nam_aeed72_idx"
                    ),
                    models.Index(
                        fields=["country_code"], name="finance_tax_country_20f849_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TaxGroupTaxes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tax",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_mappings",
                        to="taxes.tax",
                    ),
                ),
                (
                    "tax_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_mappings",
                        to="taxes.taxgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Group Mapping",
                "verbose_name_plural": "Tax Group Mappings",
                "db_table": "finance_tax_group_taxes",
                "unique_together": {("tax_group", "tax")},
            },
        ),
    ]
