# Generated by Django 5.1.11 on 2025-08-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tax",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
