# Generated by Django 5.1.11 on 2025-08-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventorySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "locations_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable multi-location inventory tracking",
                    ),
                ),
                (
                    "track_inventory",
                    models.BooleanField(
                        default=True, help_text="Track inventory levels for products"
                    ),
                ),
                (
                    "allow_negative_stock",
                    models.BooleanField(
                        default=False, help_text="Allow stock levels to go negative"
                    ),
                ),
                (
                    "auto_reorder_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable automatic reorder notifications",
                    ),
                ),
                (
                    "default_weight_unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilograms"),
                            ("lbs", "Pounds"),
                            ("g", "Grams"),
                            ("oz", "Ounces"),
                        ],
                        default="kg",
                        max_length=10,
                    ),
                ),
                (
                    "default_dimension_unit",
                    models.CharField(
                        choices=[
                            ("cm", "Centimeters"),
                            ("in", "Inches"),
                            ("m", "Meters"),
                            ("ft", "Feet"),
                        ],
                        default="cm",
                        max_length=10,
                    ),
                ),
                (
                    "enable_barcode",
                    models.BooleanField(
                        default=True, help_text="Enable barcode functionality"
                    ),
                ),
                (
                    "barcode_type",
                    models.CharField(
                        choices=[
                            ("CODE128", "Code 128"),
                            ("CODE39", "Code 39"),
                            ("EAN13", "EAN-13"),
                            ("UPC", "UPC-A"),
                            ("QR", "QR Code"),
                        ],
                        default="CODE128",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Inventory Settings",
                "verbose_name_plural": "Inventory Settings",
                "db_table": "inventory_settings",
            },
        ),
    ]
