# Generated by Django 5.1.11 on 2025-07-29 14:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_auth", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantUser",
            fields=[],
            options={
                "verbose_name": "Tenant User",
                "verbose_name_plural": "Tenant Users",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core_auth.user",),
            managers=[
                ("objects", django.db.models.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                            ("sales", "Sales Representative"),
                            ("support", "Support"),
                            ("viewer", "Viewer"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("permissions", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["role_type"], name="idx_role_type"),
                    models.Index(fields=["is_active"], name="idx_role_active"),
                    models.Index(fields=["created_at"], name="idx_role_created"),
                ],
                "unique_together": {("name", "role_type")},
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("access", "Access"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=100)),
                ("changes", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["user"], name="idx_auditlog_user"),
                    models.Index(fields=["action"], name="idx_auditlog_action"),
                    models.Index(fields=["model_name"], name="idx_auditlog_model"),
                    models.Index(fields=["timestamp"], name="idx_auditlog_timestamp"),
                    models.Index(
                        fields=["user", "timestamp"], name="idx_auditlog_user_timestamp"
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="idx_auditlog_action_timestamp",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_assigned_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_role_users",
                        to="tenant_core.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="idx_userrole_user"),
                    models.Index(fields=["role"], name="idx_userrole_role"),
                    models.Index(fields=["is_active"], name="idx_userrole_active"),
                    models.Index(fields=["assigned_at"], name="idx_userrole_assigned"),
                    models.Index(
                        fields=["user", "is_active"], name="idx_userrole_user_active"
                    ),
                    models.Index(
                        fields=["role", "is_active"], name="idx_userrole_role_active"
                    ),
                ],
                "unique_together": {("user", "role")},
            },
        ),
    ]
