# Generated by Django 5.1.11 on 2025-08-12 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('deal_id', models.AutoField(primary_key=True, serialize=False)),
                ('deal_name', models.CharField(max_length=255)),
                ('stage', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('close_date', models.DateField()),
                ('description', models.TextField(blank=True, help_text='Additional notes or description for this deal', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_column='owner_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_deals', to=settings.AUTH_USER_MODEL)),
                ('primary_contact', models.ForeignKey(blank=True, db_column='primary_contact_id', help_text='Primary contact for this deal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_deals', to='contacts.contact')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'db_table': 'deal',
                'ordering': ['-close_date'],
                'indexes': [models.Index(fields=['account'], name='idx_deal_account'), models.Index(fields=['owner'], name='idx_deal_owner'), models.Index(fields=['stage'], name='idx_deal_stage'), models.Index(fields=['created_at'], name='idx_deal_created'), models.Index(fields=['stage'], name='idx_deal_stage_idx'), models.Index(fields=['close_date'], name='idx_deal_close_date'), models.Index(fields=['amount'], name='idx_deal_amount'), models.Index(fields=['account'], name='idx_deal_account_idx'), models.Index(fields=['owner'], name='idx_deal_owner_idx'), models.Index(fields=['primary_contact'], name='idx_deal_primary_contact')],
            },
        ),
    ]
