# Generated by Django 5.1.11 on 2025-08-21 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="A unique ID for the currency",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        db_index=True,
                        help_text="A unique code for the currency (e.g., USD, EUR, AUD)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "currency_name",
                    models.CharField(
                        help_text="The name for the currency (e.g., 'USD- US Dollar')",
                        max_length=200,
                    ),
                ),
                (
                    "currency_symbol",
                    models.CharField(
                        help_text="A unique symbol for the currency (e.g., $, €, £)",
                        max_length=4,
                    ),
                ),
                (
                    "price_precision",
                    models.IntegerField(
                        default=2,
                        help_text="The precision for the price in decimals",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "currency_format",
                    models.CharField(
                        default="1,234,567.89",
                        help_text="The format for the currency to be displayed",
                        max_length=100,
                    ),
                ),
                (
                    "is_base_currency",
                    models.BooleanField(
                        default=False,
                        help_text="If the specified currency is the base currency of the organization or not",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=10,
                        default=1.0,
                        help_text="Foreign Exchange rate for the currency",
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True,
                        help_text="Date from when the currency will be in effect",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "db_table": "currencies",
                "ordering": ["currency_code"],
                "indexes": [
                    models.Index(
                        fields=["currency_code"], name="currencies_currenc_b79b71_idx"
                    ),
                    models.Index(
                        fields=["is_base_currency"],
                        name="currencies_is_base_b0660e_idx",
                    ),
                ],
            },
        ),
    ]
