# Generated by Django 5.1.11 on 2025-08-12 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, help_text='Product manufacturer', max_length=100, null=True)),
                ('category', models.CharField(blank=True, help_text='Product category', max_length=100, null=True)),
                ('part_number', models.CharField(blank=True, help_text='Manufacturer part number', max_length=100, null=True)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (box, kg, cm, etc.)', max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, help_text='Current selling price', max_digits=10, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type', models.CharField(choices=[('inventory', 'Inventory'), ('non-inventory', 'Non-Inventory'), ('service', 'Service')], default='inventory', max_length=50, verbose_name='Product Type')),
                ('billing_frequency', models.CharField(choices=[('one-time', 'One-time'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='one-time', max_length=50)),
                ('term', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.IntegerField(default=0, help_text='Current stock quantity')),
                ('vendor_name', models.CharField(blank=True, help_text='Primary vendor name', max_length=100, null=True)),
                ('vendor_price', models.DecimalField(blank=True, decimal_places=2, help_text='Vendor cost price', max_digits=10, null=True)),
                ('product_condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished'), ('damaged', 'Damaged')], default='new', help_text='Condition of the product', max_length=20)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['sku'], name='idx_product_sku'), models.Index(fields=['name'], name='idx_product_name'), models.Index(fields=['created_at'], name='idx_product_created'), models.Index(fields=['manufacturer'], name='idx_product_manufacturer'), models.Index(fields=['category'], name='idx_product_category'), models.Index(fields=['part_number'], name='idx_product_part_number'), models.Index(fields=['vendor_name'], name='idx_product_vendor')],
            },
        ),
    ]
