# Generated by Django 5.1.11 on 2025-08-19 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_unified_contact_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="accounttransaction",
            name="finance_acc_custome_5e65b0_idx",
        ),
        migrations.RemoveIndex(
            model_name="accounttransaction",
            name="finance_acc_vendor__fb3841_idx",
        ),
        migrations.AddIndex(
            model_name="accounttransaction",
            index=models.Index(
                fields=["contact_id", "transaction_date"],
                name="finance_acc_contact_2506de_idx",
            ),
        ),
    ]
