# Generated by Django 5.1.11 on 2025-08-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_accounttransaction_finance_acc_custome_5e65b0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='is_default_account',
            field=models.BooleanField(default=False, help_text='Indicates if this is a default system account'),
        ),
    ]
