# Generated by Django 5.1.11 on 2025-08-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_chartofaccount_is_default_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartofaccount',
            name='is_default_account',
        ),
    ]
