# Generated by Django 5.1.11 on 2025-08-22 09:25

import services.finance.accounting.models.accounts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_remove_chartofaccount_is_default_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='currency_code',
            field=models.CharField(default=services.finance.accounting.models.accounts.get_base_currency_code, help_text='Currency code (e.g., USD, EUR, GBP)', max_length=10),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='currency_id',
            field=models.CharField(default=services.finance.accounting.models.accounts.get_base_currency_id, help_text='Currency identifier', max_length=50),
        ),
    ]
