# Generated by Django 5.1.11 on 2025-08-12 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0001_initial'),
        ('customers', '0001_initial'),
        ('deals', '0001_initial'),
        ('estimates', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Shipping fee for this document', max_digits=10)),
                ('shipping_vat_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='VAT percentage for shipping (0-100)', max_digits=5)),
                ('rush_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Rush processing fee for this document', max_digits=10)),
                ('sales_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_order_number', models.CharField(help_text="Unique sales order number, e.g., 'SO-2024-001'", max_length=50, unique=True)),
                ('reference_number', models.CharField(blank=True, help_text='Customer reference number', max_length=100, null=True)),
                ('po_number', models.CharField(blank=True, help_text='Customer purchase order number', max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', help_text='Current status of the sales order', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of all line item subtotals (before VAT)', max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of all line item totals (includes VAT)', max_digits=14)),
                ('sales_order_date', models.DateField(help_text='Date when sales order was created')),
                ('expected_shipment_date', models.DateField(blank=True, help_text='Expected date of shipment', null=True)),
                ('actual_shipment_date', models.DateField(blank=True, help_text='Actual date when order was shipped', null=True)),
                ('delivery_date', models.DateField(blank=True, help_text='Date when order was delivered', null=True)),
                ('payment_terms', models.CharField(choices=[('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('due_on_receipt', 'Due on Receipt'), ('custom', 'Custom Terms')], default='net_30', help_text='Payment terms for this sales order', max_length=20)),
                ('custom_payment_terms', models.CharField(blank=True, help_text='Custom payment terms description', max_length=200, null=True)),
                ('delivery_method', models.CharField(choices=[('standard', 'Standard Shipping'), ('express', 'Express Shipping'), ('overnight', 'Overnight Delivery'), ('pickup', 'Customer Pickup'), ('custom', 'Custom Delivery')], default='standard', help_text='Delivery method for this order', max_length=50)),
                ('custom_delivery_method', models.CharField(blank=True, help_text="Custom delivery method if 'custom' is selected", max_length=100, null=True)),
                ('billing_attention', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_street', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_zip_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_attention', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_street', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_zip_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_country', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_notes', models.TextField(blank=True, help_text='Notes from/for the customer', null=True)),
                ('terms_conditions', models.TextField(blank=True, help_text='Terms and conditions for this sales order', null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes (not shown to customer)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='account_id', help_text='Account this sales order is for (required)', on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='accounts.account')),
                ('contact', models.ForeignKey(blank=True, db_column='contact_id', help_text='Primary contact person for this sales order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', help_text='Customer this sales order is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='customers.financecontact')),
                ('deal', models.ForeignKey(blank=True, db_column='deal_id', help_text='Associated deal/opportunity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='deals.deal')),
                ('estimate', models.ForeignKey(blank=True, db_column='estimate_id', help_text='Source estimate this sales order was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='estimates.estimate')),
                ('owner', models.ForeignKey(blank=True, db_column='owner_id', help_text='Sales rep/owner of this sales order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_sales_orders', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
                'db_table': 'sales_order',
                'ordering': ['-sales_order_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLineItem',
            fields=[
                ('line_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, help_text='Custom description (can override product description)', null=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity ordered', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit (can override product price)', max_digits=10)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (0-100)', max_digits=5)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='VAT percentage for this line item (0-100)', max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated VAT amount for this line item', max_digits=14)),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='(quantity × unit_price) - discount', max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=0.0, help_text='line_subtotal + vat_amount', max_digits=14)),
                ('sort_order', models.PositiveIntegerField(default=1, help_text='Display order of this line item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(db_column='product_id', help_text='Product/service for this line item', on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_line_items', to='products.product')),
                ('sales_order', models.ForeignKey(db_column='sales_order_id', help_text='Sales order this line item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='sales_orders.salesorder')),
            ],
            options={
                'verbose_name': 'Sales Order Line Item',
                'verbose_name_plural': 'Sales Order Line Items',
                'db_table': 'sales_order_line_item',
                'ordering': ['sort_order', 'line_item_id'],
            },
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['sales_order_number'], name='idx_so_number'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer'], name='idx_so_customer'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['account'], name='idx_so_account'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['deal'], name='idx_so_deal'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['contact'], name='idx_so_contact'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['owner'], name='idx_so_owner'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['estimate'], name='idx_so_estimate'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['created_at'], name='idx_so_created'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status'], name='idx_so_status'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['sales_order_date'], name='idx_so_date'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['expected_shipment_date'], name='idx_so_exp_ship_date'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('sales_order_number',), name='unique_so_number_per_schema'),
        ),
        migrations.AddIndex(
            model_name='salesorderlineitem',
            index=models.Index(fields=['sales_order'], name='idx_so_line_sales_order'),
        ),
        migrations.AddIndex(
            model_name='salesorderlineitem',
            index=models.Index(fields=['product'], name='idx_so_line_product'),
        ),
        migrations.AddIndex(
            model_name='salesorderlineitem',
            index=models.Index(fields=['vat_rate'], name='idx_so_line_vat_rate'),
        ),
        migrations.AddIndex(
            model_name='salesorderlineitem',
            index=models.Index(fields=['sort_order'], name='idx_so_line_sort_order'),
        ),
    ]
